export enum ItemCode {
    cat = 1,
    dog,
    upskillTest,
    upskillDev,
    upskillBA,
    observe,
    selfstart,
    seat,
    coffee,
    coffeemachine,
    cupcake,
    donut,
    pizza,
    banana,
    toast,
    keyboard,
    x_bafortest,
    x_bafordev,
    x_testforba,
    x_testfordev,
    x_devforba,
    x_devfortest,
    poster,
    crystalball,
    statue,
    statue2 //TODO: simple bling 
}
